[tool.isort]
profile = "black"
line_length = 120
known_mindspore = ["mindspore", "torch"]
known_first_party = ["vc"]
sections = ["FUTURE", "STDLIB", "THIRDPARTY", "MINDSPORE", "FIRSTPARTY", "LOCALFOLDER"]

[tool.black]
line-length = 120
